package euler.problem2;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

public class Problem2 {

    public static void main(String[] args) {


        System.out.println(fibonacciSum(4000000));
    }

    public static long fibonacciSum(int n) {
        long earlier2 = 1;
        long earlier1 = 2;
        long fibonacci = earlier2 + earlier1;
        long sum = 2;

        while (fibonacci < n) {
            if (fibonacci % 2 == 0) {
                sum += fibonacci;
            }

            earlier2 = earlier1;
            earlier1 = fibonacci;
            fibonacci = earlier1 + earlier2;
        }
        return sum;
    }
}
